/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login
         * @description Initiate OAuth flow with Google.
         */
        get: operations["login_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth
         * @description OAuth callback - complete authentication.
         */
        get: operations["auth_auth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Logout */
        get: operations["logout_logout_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get current authenticated account
         */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get
         * @description Get account details for the authenticated user.
         */
        get: operations["get_manage__account_id___get"];
        put?: never;
        post?: never;
        /**
         * Delete Account Endpoint
         * @description Delete the authenticated user's account.
         */
        delete: operations["delete_account_endpoint_manage__account_id___delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/apis/{api_id}/worksheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Worksheets For Api
         * @description Get all worksheet names for an API from cache.
         *
         *     Returns only worksheets that have been accessed at least once.
         *     For a complete list including never-accessed sheets, fetch directly from Google.
         */
        get: operations["get_worksheets_for_api_manage__account_id__apis__api_id__worksheets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/apis/{api_id}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Watch Channels
         * @description Get all watch channels for an API
         */
        get: operations["get_watch_channels_manage__account_id__apis__api_id__notifications_get"];
        put?: never;
        /**
         * Create Watch Channel
         * @description Create or update a new watch channel for an API
         */
        post: operations["create_watch_channel_manage__account_id__apis__api_id__notifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/apis/{api_id}/notifications/{channel_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Watch Channel */
        delete: operations["delete_watch_channel_manage__account_id__apis__api_id__notifications__channel_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/apis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Apis For Account
         * @description Get all APIs for an account.
         */
        get: operations["get_apis_for_account_manage__account_id__apis_get"];
        put?: never;
        /**
         * Create Api
         * @description Create a new API endpoint for a Google Sheet.
         *
         *     The account_id from the path determines the owner of the API.
         *     User must have permissions to manage this account (self or org).
         */
        post: operations["create_api_manage__account_id__apis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/apis/{api_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Api
         * @description Delete an API endpoint.
         */
        delete: operations["delete_api_manage__account_id__apis__api_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Api
         * @description Update an API with partial updates.
         */
        patch: operations["update_api_manage__account_id__apis__api_id__patch"];
        trace?: never;
    };
    "/manage/{account_id}/apis/{api_id}/refresh-title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Spreadsheet Title
         * @description Manually refresh the spreadsheet title from Google Sheets.
         */
        post: operations["refresh_spreadsheet_title_manage__account_id__apis__api_id__refresh_title_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/posts/{post_key}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Categories For Post
         * @description Get all categories for a specific post.
         */
        get: operations["get_categories_for_post_manage__account_id__posts__post_key__categories_get"];
        put?: never;
        /**
         * Add Category To Post
         * @description Add a category to a post.
         */
        post: operations["add_category_to_post_manage__account_id__posts__post_key__categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/posts/{post_key}/categories/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Category From Post
         * @description Remove a category from a post.
         */
        delete: operations["remove_category_from_post_manage__account_id__posts__post_key__categories__category__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/posts/{post_key}/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Webhooks */
        get: operations["get_webhooks_manage__account_id__posts__post_key__webhooks_get"];
        put?: never;
        /** Create Webhook */
        post: operations["create_webhook_manage__account_id__posts__post_key__webhooks_post"];
        /** Delete Webhook */
        delete: operations["delete_webhook_manage__account_id__posts__post_key__webhooks_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/posts/{post_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Post Data */
        post: operations["refresh_post_data_manage__account_id__posts__post_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Posts For Account
         * @description Get all APIs for an account.
         */
        get: operations["get_posts_for_account_manage__account_id__posts_get"];
        put?: never;
        /**
         * Create Post
         * @description Create a new API endpoint for a Google Sheet.
         *
         *     The account_id from the path determines the owner of the API.
         *     User must have permissions to manage this account (self or org).
         */
        post: operations["create_post_manage__account_id__posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Api
         * @description Delete an API endpoint.
         */
        delete: operations["delete_api_manage__account_id__posts__post_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/organizations/{org_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Memberships For Organization
         * @description Get all memberships for an org/account.
         */
        get: operations["get_memberships_for_organization_manage__account_id__organizations__org_id__memberships_get"];
        put?: never;
        /** Create Memberships */
        post: operations["create_memberships_manage__account_id__organizations__org_id__memberships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Organizations
         * @description Get all memberships for an org/account.
         */
        get: operations["get_organizations_manage__account_id__organizations_get"];
        put?: never;
        /** Create Organization */
        post: operations["create_organization_manage__account_id__organizations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Organization
         * @description Get all memberships for an org/account.
         */
        get: operations["get_organization_manage__account_id__organizations__org_id__get"];
        put?: never;
        post?: never;
        /** Delete Organization */
        delete: operations["delete_organization_manage__account_id__organizations__org_id__delete"];
        options?: never;
        /**
         * Head Organization
         * @description Get all memberships for an org/account.
         */
        head: operations["head_organization_manage__account_id__organizations__org_id__head"];
        patch?: never;
        trace?: never;
    };
    "/manage/{account_id}/analytics/{resource_type}/{resource_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Resource Analytics
         * @description Get analytics logs for a specific API or Post within a time range.
         */
        get: operations["get_resource_analytics_manage__account_id__analytics__resource_type___resource_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/stripe-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stripe Webhook
         * @description Handle Stripe webhook events.
         *
         *     Processes events such as:
         *     - checkout.session.completed: Upgrade user to premium
         *     - invoice.paid: Update billing period for renewal
         *     - customer.subscription.deleted: Downgrade user from premium
         */
        post: operations["stripe_webhook_billing_stripe_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/create-checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Checkout
         * @description Create a Stripe checkout session for premium subscription.
         *
         *     Returns a URL to redirect the user to Stripe's checkout page.
         */
        post: operations["create_checkout_billing_create_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountRead */
        AccountRead: {
            /**
             * Id
             * @description The name/ID of the account (alphanumeric and hyphens only)
             */
            id: string;
            /** Account Status */
            account_status: string;
            /** Display Name */
            display_name: string;
            /**
             * Email
             * @description Email exists for users, not orgs.
             */
            email: string | null;
        };
        /** AnalyticsLogRead */
        AnalyticsLogRead: {
            /**
             * Owner Id
             * @description The name/ID of the account (alphanumeric and hyphens only)
             */
            owner_id: string;
            /** Resource Id */
            resource_id: string;
            /**
             * Resource Type
             * @enum {string}
             */
            resource_type: "api" | "post";
            /** Status Code */
            status_code: number;
            /** Cache Result */
            cache_result: string;
            /** Path */
            path: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Request Id */
            request_id: string;
        };
        /** ApiCreateRead */
        ApiCreateRead: {
            /**
             * Api Key
             * @description ID of the newly created API.
             */
            api_key: string;
        };
        /**
         * ApiCreateRequest
         * @description Schema for API creation request from client.
         *
         *     Note: owner_id comes from the path parameter, not the request body.
         */
        ApiCreateRequest: {
            /**
             * Google Sheet Id
             * @description Google Sheet ID this API serves
             */
            google_sheet_id: string;
            /**
             * Frozen
             * @description Whether API is frozen/disabled
             * @default false
             */
            frozen: boolean;
            /**
             * Cache Duration
             * @description Cache duration in seconds for API responses
             */
            cache_duration: number;
        };
        /**
         * ApiRead
         * @description Schema for returning API data to clients.
         */
        ApiRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * Google Sheet Id
             * @description Google Sheet ID this API serves
             */
            google_sheet_id: string;
            /**
             * Frozen
             * @description Whether API is frozen/disabled
             * @default false
             */
            frozen: boolean;
            /**
             * Cache Duration
             * @description Cache duration in seconds for API responses
             */
            cache_duration: number;
            /**
             * Api Key
             * @description Unique API key identifier
             */
            api_key: string;
            /**
             * Owner Id
             * @description Account ID of the owner
             */
            owner_id: string;
            /**
             * Spreadsheet Title
             * @description Cached title of the Google Spreadsheet
             */
            spreadsheet_title?: string | null;
        };
        /**
         * ApiUpdate
         * @description Schema for updating an API - all fields optional for partial updates.
         */
        ApiUpdate: {
            /** Cache Duration */
            cache_duration?: number | null;
        };
        /**
         * ApiWatchChannelCreate
         * @description Main model for registration/creation of a watch channel
         */
        ApiWatchChannelCreate: {
            /**
             * Api Key
             * @description The Jedwal API this watch channel is for
             */
            api_key: string;
            /**
             * Owner Id
             * @description Owner of the parent API
             */
            owner_id: string;
            /**
             * Webhook Url
             * @description The URL to notify the user at. Note: not supplied to Google. This is used internally
             */
            webhook_url: string;
            /**
             * Name
             * @description Human-readable name for this watch channel
             */
            name: string;
        };
        /**
         * ApiWatchChannelRead
         * @description Response model of a watch channel
         */
        ApiWatchChannelRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * Api Key
             * @description The Jedwal API this watch channel is for
             */
            api_key: string;
            /**
             * Owner Id
             * @description Owner of the parent API
             */
            owner_id: string;
            /**
             * Webhook Url
             * @description The URL to notify the user at. Note: not supplied to Google. This is used internally
             */
            webhook_url: string;
            /**
             * Name
             * @description Human-readable name for this watch channel
             */
            name: string;
            /**
             * Channel Id
             * @description The unique id of the watch channel
             */
            channel_id: string;
        };
        /**
         * CategoryCreate
         * @description Schema for adding a category to a post.
         */
        CategoryCreate: {
            /**
             * Category
             * @description Category name to add
             */
            category: string;
        };
        /**
         * CategoryRead
         * @description Schema for returning category information.
         */
        CategoryRead: {
            /**
             * Category
             * @description Category name
             */
            category: string;
        };
        /**
         * CheckoutSession
         * @description Checkout session response.
         */
        CheckoutSession: {
            /** Url */
            url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MembershipCreate */
        MembershipCreate: {
            /**
             * Member Type
             * @description Role the account has in the org.
             * @enum {string}
             */
            member_type: "owner" | "member";
            /**
             * Email
             * Format: email
             * @description The email of the user to invite.
             */
            email: string;
        };
        /** MembershipCreateRequest */
        MembershipCreateRequest: {
            /** Memberships */
            memberships: components["schemas"]["MembershipCreate"][];
        };
        /**
         * MembershipRead
         * @description Membership item for public reads
         */
        MembershipRead: {
            /**
             * Account Id
             * @description The account in the org
             */
            account_id: string;
            /**
             * Organization Id
             * @description The org the account belongs to
             */
            organization_id: string;
            /**
             * Member Type
             * @description Role the account has in the org.
             * @enum {string}
             */
            member_type: "owner" | "member";
            /**
             * Joined At
             * Format: date-time
             * @description When the account joined the org
             */
            joined_at: string;
        };
        /**
         * Organization
         * @description Organization domain model
         */
        Organization: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * Account Id
             * @description Unique org/account identifier
             */
            account_id: string;
            /**
             * Display Name
             * @description User display name
             */
            display_name: string;
            /**
             * Account Status
             * @description Account status
             * @enum {string}
             */
            account_status: "free" | "premium";
            /**
             * Billing Account Id
             * @description ID of the account used for billing
             */
            billing_account_id: string;
        };
        /** OrganizationCreateRequest */
        OrganizationCreateRequest: {
            /**
             * Organization Name
             * @description The name of the organization to create
             */
            organization_name: string;
            /**
             * Memberships
             * @description Account emails to invite
             */
            memberships: string[];
        };
        /** PostCreateRead */
        PostCreateRead: {
            /**
             * Post Key
             * @description Post ID of the newly created post.
             */
            post_key: string;
        };
        /** PostCreateRequest */
        PostCreateRequest: {
            /**
             * Post Key
             * @description The name/ID/slug of the post (alphanumeric and hyphens only)
             */
            post_key: string;
            /**
             * Google Doc Id
             * @description The Google Doc ID to create a post from
             */
            google_doc_id: string;
        };
        /** PostRead */
        PostRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * Post Key
             * @description The name/ID/slug of the post (alphanumeric and hyphens only)
             */
            post_key: string;
            /**
             * Owner Id
             * @description The name/ID of the account (alphanumeric and hyphens only)
             */
            owner_id: string;
            /** Title */
            title: string;
            /** Google Doc Id */
            google_doc_id: string;
            /**
             * Categories
             * @description Post categories
             */
            categories?: string[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Webhook */
        Webhook: {
            /** Url */
            url: string;
            /**
             * Method
             * @enum {string}
             */
            method: "GET" | "POST";
            /** Name */
            name?: string | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** WebhookCreateRequest */
        WebhookCreateRequest: {
            /** Url */
            url: string;
            /**
             * Method
             * @enum {string}
             */
            method: "GET" | "POST";
            /** Name */
            name?: string | null;
            /** Payload */
            payload?: string | null;
        };
        /** WebhookDeleteRequest */
        WebhookDeleteRequest: {
            /** Url */
            url: string;
            /**
             * Method
             * @enum {string}
             */
            method: "GET" | "POST";
            /** Name */
            name?: string | null;
        };
        /** WebhooksRead */
        WebhooksRead: {
            /**
             * Account Id
             * @description The account owner of the post
             */
            account_id: string;
            /**
             * Post Id
             * @description The post ID
             */
            post_id: string;
            /**
             * Webhooks
             * @description The webhook configs for this post
             */
            webhooks: components["schemas"]["Webhook"][];
        };
        /**
         * WorksheetNamesRead
         * @description Response containing worksheet names for an API.
         */
        WorksheetNamesRead: {
            /**
             * Worksheets
             * @description List of worksheet names from Google Sheets
             */
            worksheets: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_auth_get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_logout_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manage__account_id___get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_account_endpoint_manage__account_id___delete: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_worksheets_for_api_manage__account_id__apis__api_id__worksheets_get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                api_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorksheetNamesRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_watch_channels_manage__account_id__apis__api_id__notifications_get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                api_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiWatchChannelRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_watch_channel_manage__account_id__apis__api_id__notifications_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiWatchChannelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiWatchChannelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_watch_channel_manage__account_id__apis__api_id__notifications__channel_id__delete: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                api_id: string;
                channel_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_apis_for_account_manage__account_id__apis_get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_manage__account_id__apis_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiCreateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_manage__account_id__apis__api_id__delete: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                api_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_api_manage__account_id__apis__api_id__patch: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                api_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_spreadsheet_title_manage__account_id__apis__api_id__refresh_title_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                api_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_categories_for_post_manage__account_id__posts__post_key__categories_get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                post_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_category_to_post_manage__account_id__posts__post_key__categories_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                post_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_category_from_post_manage__account_id__posts__post_key__categories__category__delete: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                post_key: string;
                category: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_webhooks_manage__account_id__posts__post_key__webhooks_get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                post_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhooksRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_webhook_manage__account_id__posts__post_key__webhooks_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                post_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_webhook_manage__account_id__posts__post_key__webhooks_delete: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                post_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_post_data_manage__account_id__posts__post_id__refresh_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_posts_for_account_manage__account_id__posts_get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_post_manage__account_id__posts_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostCreateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_manage__account_id__posts__post_id__delete: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_memberships_for_organization_manage__account_id__organizations__org_id__memberships_get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                org_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_memberships_manage__account_id__organizations__org_id__memberships_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                org_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organizations_manage__account_id__organizations_get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_organization_manage__account_id__organizations_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_organization_manage__account_id__organizations__org_id__get: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_organization_manage__account_id__organizations__org_id__delete: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_organization_manage__account_id__organizations__org_id__head: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resource_analytics_manage__account_id__analytics__resource_type___resource_id__get: {
        parameters: {
            query?: {
                /** @description ISO 8601 timestamp (e.g., 2025-01-01T00:00:00Z) */
                start_time?: string | null;
                /** @description ISO 8601 timestamp (e.g., 2025-01-31T23:59:59Z) */
                end_time?: string | null;
                table_name?: string | null;
            };
            header?: never;
            path: {
                account_id: string;
                resource_type: "api" | "post";
                resource_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsLogRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stripe_webhook_billing_stripe_webhook_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: {
                "Stripe-Signature"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_billing_create_checkout_post: {
        parameters: {
            query?: {
                table_name?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
